package de.hsrm.wp.springboot.testenv_sakila.controller;

import de.hsrm.wp.springboot.testenv_sakila.model.Film;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import de.hsrm.wp.springboot.testenv_sakila.repository.FilmRepository;

@Controller // This means that this class is a Controller
public class TestEasyRest {

    @Autowired // This means to get the bean called filmRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private FilmRepository filmRepository;

    @GetMapping("/getFilms")
    public @ResponseBody
    Iterable<Film> getAllFilms() {
        // This returns a JSON or XML with the users
        // Select * from film
        return filmRepository.findAll();
    }
}
